<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="format-xslt.xsl"?>
<!--	burgers.xml
	Author: Cody Lewis - c3283349
	Date: 18-08-2017
	Last Modified: 14-09-2017
	Description:
	Show the names and general structure of the xml tags for the Online Food Delivery Website -->
<!DOCTYPE foodDel [
	<!ELEMENT foodDel (cuisine)>
	<!ELEMENT cuisine (restaurant+)>
	<!ATTLIST cuisine type (Italian|Burger) #REQUIRED>
	<!ELEMENT restaurant (name,logo?,picture+,URL,address,phone+,openingHours,delivery,description)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT logo (#PCDATA)>
	<!ELEMENT picture (#PCDATA)>
	<!ELEMENT URL (#PCDATA)>
	<!ELEMENT address (number,street,suburb,state,postcode,country)>
	<!ELEMENT number (#PCDATA)>
	<!ELEMENT street (#PCDATA)>
	<!ELEMENT suburb (#PCDATA)>
	<!ELEMENT state (#PCDATA)>
	<!ELEMENT postcode (#PCDATA)>
	<!ELEMENT country (#PCDATA)>
	<!ELEMENT phone (#PCDATA)>
	<!ELEMENT openingHours (date+)>
	<!ELEMENT date (open,close)>
	<!ATTLIST date day (mon|tue|wed|thu|fri|sat|sun|mon-fri|mon-thu|wed-sat|tue-fri|tue-sun|wed-sun|mon-sun) #REQUIRED>
	<!ELEMENT open (#PCDATA)>
	<!ELEMENT close (#PCDATA)>
	<!ELEMENT delivery (minimumPrice,fee)>
	<!ELEMENT minimumPrice (#PCDATA)>
	<!ELEMENT fee (#PCDATA)>
	<!ELEMENT description (#PCDATA)>
	<!ENTITY r "Restaurant">
	<!ENTITY b "Burger">
	<!ENTITY i "Italian">
	<!ENTITY pp "per person">
	<!ENTITY st "Street">
	<!ENTITY rd "Road">
	<!ENTITY new "Newcastle">
	<!ENTITY nsw "New South Wales">
	<!ENTITY au "Australia">
]>
<foodDel>
	<cuisine type="&b;">
		<restaurant>
			<name>Newy &b; Co.</name>
			<logo>./images/newy&b;CoLogo.png</logo>
			<picture>./images/newy&b;CoPic.jpg</picture>
			<URL>http://newyburgerco.com.au/</URL>
			<address>
				<number>459</number>
				<street>Hunter &st;</street>
				<suburb>&new;</suburb>
				<state>&nsw;</state>
				<postcode>2300</postcode>
				<country>&au;</country>
			</address>
			<phone>0438845956</phone>
			<openingHours>
				<date day="wed-sat">
					<open>11:30am</open>
					<close>9:00pm</close>
				</date>
				<date day="sun">
					<open>11:30am</open>
					<close>8:00pm</close>
				</date>
			</openingHours>
			<delivery>
				<minimumPrice>$12</minimumPrice>
				<fee>$4 &pp;</fee>
			</delivery>
			<description>Bringing tasty burgers and catering to Newy and Maito!</description>
		</restaurant>
		<restaurant>
			<name>&b; Urge</name>
			<logo>./images/burgerUrgeLogo.png</logo>
			<picture>./images/burgerUrgePic.jpg</picture>
			<URL>http://burgerurge.com.au/</URL>
			<address>
				<number>387</number>
				<street>Lake &rd;</street>
				<suburb>Glendale</suburb>
				<state>&nsw;</state>
				<postcode>2285</postcode>
				<country>&au;</country>
			</address>
			<phone>0249537653</phone>
			<openingHours>
				<date day="mon-sun">
					<open>11:30am</open>
					<close>9:00pm</close>
				</date>
			</openingHours>
			<delivery>
				<minimumPrice>$10</minimumPrice>
				<fee>$3</fee>
			</delivery>
			<description>Local chain fixing up heaping gourmet burgers with eclectic fillings and playful names.</description>
		</restaurant>
		<restaurant>
			<name>Rascal</name>
			<logo>./images/rascalLogo.png</logo>
			<picture>./images/rascalPic.jpg</picture>
			<URL>http://eatrascal.com.au/</URL>
			<address>
				<number>1/266</number>
				<street>King &st;</street>
				<suburb>&new;</suburb>
				<state>&nsw;</state>
				<postcode>2300</postcode>
				<country>&au;</country>
			</address>
			<phone>0240472375</phone>
			<openingHours>
				<date day="mon">
					<open>11:00am</open>
					<close>4:00pm</close>
				</date>
				<date day="wed-sun">
					<open>11:00am</open>
					<close>9:00pm</close>
				</date>
			</openingHours>
			<delivery>
				<minimumPrice>$9.90</minimumPrice>
				<fee>$2</fee>
			</delivery>
			<description>Burgers. Chicken. Anarchy... Hatted chefs building burgers, thier own butcher personally sourcing the meat and hunting down the chickens, house made everything; including mind blowing sauces</description>
		</restaurant>
	</cuisine>
</foodDel>
