<?xml-stylesheet type="text/xsl" href="format-xslt.xsl"?>
<!--	italian.xml
	Author: Cody Lewis - c3283349
	Date: 18-08-2017
	Last Modified: 14-09-2017
	Description:
	Show the names and general structure of the xml tags for the Online Food Delivery Website -->
<!DOCTYPE foodDel [
	<!ELEMENT foodDel (cuisine)>
		<!ELEMENT cuisine (restaurant+)>
		<!ATTLIST cuisine type (Italian|Burger) #REQUIRED>
			<!ELEMENT restaurant (name,logo?,picture+,URL,address,phone+,openingHours,delivery,description)>
				<!ELEMENT name (#PCDATA)>
				<!ELEMENT logo (#PCDATA)>
				<!ELEMENT picture (#PCDATA)>
				<!ELEMENT URL (#PCDATA)>
				<!ELEMENT address (number,street,suburb,state,postcode,country)>
					<!ELEMENT number (#PCDATA)>
					<!ELEMENT street (#PCDATA)>
					<!ELEMENT suburb (#PCDATA)>
					<!ELEMENT state (#PCDATA)>
					<!ELEMENT postcode (#PCDATA)>
					<!ELEMENT country (#PCDATA)>
				<!ELEMENT phone (#PCDATA)>
				<!ELEMENT openingHours (date+)>
					<!ELEMENT date (open,close)>
					<!ATTLIST date day (mon|tue|wed|thu|fri|sat|sun|mon-fri|mon-thu|wed-sat|tue-fri|tue-sun|wed-sun|mon-sun) #REQUIRED>
						<!ELEMENT open (#PCDATA)>
						<!ELEMENT close (#PCDATA)>
				<!ELEMENT delivery (minimumPrice,fee)>
					<!ELEMENT minimumPrice (#PCDATA)>
					<!ELEMENT fee (#PCDATA)>
				<!ELEMENT description (#PCDATA)>
	<!ENTITY r "Restaurant">
	<!ENTITY b "Burger">
	<!ENTITY i "Italian">
	<!ENTITY pp "per person">
	<!ENTITY st "Street">
	<!ENTITY rd "Road">
	<!ENTITY new "Newcastle">
	<!ENTITY nsw "New South Wales">
	<!ENTITY au "Australia">
]>
<foodDel>
	<cuisine type="&i;">
		<restaurant>
			<name>Verde Luna</name>
			<logo>./images/verdeLogo.jpg</logo>
			<picture>./images/verdePic.jpg</picture>
			<URL>http://www.verdeluna.com.au/</URL>
			<address>
				<number>115</number>
				<street>Tudor &st;</street>
				<suburb>Hamilton</suburb>
				<state>&nsw;</state>
				<postcode>2303</postcode>
				<country>&au;</country>
			</address>
			<phone>049613949</phone>
			<openingHours>
				<date day="tue-sun">
					<open>11:30am</open>
					<close>9:00pm</close>
				</date>
			</openingHours>
			<delivery>
				<minimumPrice>$14.90</minimumPrice>
				<fee>$3</fee>
			</delivery>
			<description>
				Relaxed trattoria with indoor/outdoor seating, whipping up traditional Italian dishes and pizzas.
			</description>
		</restaurant>
		<restaurant>
			<name>Una Volta</name>
			<logo>./images/voltaLogo.jpg</logo>
			<picture>./images/voltaPic.jpg</picture>
			<picture>./images/voltaPic1.jpg</picture>
			<picture>./images/voltaPic2.jpg</picture>
			<URL>http://restaurantwebx.com/UnaVolta/</URL>
			<address>
				<number>110</number>
				<street>King &st;</street>
				<suburb>&new;</suburb>
				<state>&nsw;</state>
				<postcode>2300</postcode>
				<country>&au;</country>
			</address>
			<phone>0434700257</phone>
			<openingHours>
				<date day="wed-sat">
					<open>6:00pm</open>
					<close>11:00pm</close>
				</date>
			</openingHours>
			<delivery>
				<minimumPrice>$25</minimumPrice>
				<fee>$5</fee>
			</delivery>
			<description>This fixed menu restaurant uses high quality, seasonal ingredients for their changing menu.</description>
		</restaurant>
		<restaurant>
			<name>El Nonno</name>
			<logo>./images/nonnoLogo.jpg</logo>
			<picture>./images/nonnoPic.jpg</picture>
			<picture>./images/nonnoPic1.jpg</picture>
			<URL>http://www.elnonno.com.au/</URL>
			<address>
				<number>79</number>
				<street>Beaumont &st;</street>
				<suburb>Hamilton</suburb>
				<state>&nsw;</state>
				<postcode>2303</postcode>
				<country>&au;</country>
			</address>
			<phone>0249625723</phone>
			<openingHours>
				<date day="tue-fri">
					<open>11:30am</open>
					<close>9:00pm</close>
				</date>
				<date day="sat">
					<open>4:00pm</open>
					<close>9:00pm</close>
				</date>
			</openingHours>
			<delivery>
				<minimumPrice>$20</minimumPrice>
				<fee>$4</fee>
			</delivery>
			<description>Italian dishes served at outdoor tables and in a smart dining room with pictures on the walls.</description>
		</restaurant>
	</cuisine>
</foodDel>
